baseURL = "https://1000wordsperday.com/"
title = "Black & Light"
author = "David Hamp-Gonsalves"
canonifyurls = true
languagecode = "en"
theme = "black-and-light"

pygmentsstyle       = "bw"
pygmentscodefences  = true

[params]
  sitename = "1000 Words per Day"
  disableWebFonts = false

[[menu.main]]
    name = "About"
    url  = "https://github.com/sgignoux"